PROGRAM  := test_merge.exe
MY_CFLAGS =  -I ./ \
	-I ../../depends/nxjsoncpp \
	-I ../../depends/nxtools \

LIB_FLAG = -lpthread \

SRCDIRS   = ./  \
	../../depends/nxjsoncpp \
	../../depends/nxtools \

include ../makefile.inc
