PROGRAM  := test_tcp.exe
MY_CFLAGS =  -I ./ \
	-I ../../depends/utils \
	-I ../../depends/nxjsoncpp \
	-I ../../depends/nxcrypto \
	-I ../../depends/nxtools \

LIB_FLAG = -lpthread -lz -lcrypto\
	-L../../depends/utils -lutils \

SRCDIRS   = ./  \
	../../depends/nxjsoncpp \
	../../depends/nxcrypto \
	../../depends/nxtools \

include ../makefile.inc
