PROGRAM  := unit_test.exe
MY_CFLAGS =  -I ./ \
	-I ../../depends/nxtools \

LIB_FLAG = -lpthread -lz -lcrypto \
	-L../ -lboost_unit_test_framework \

SRCDIRS   = ./  \
	../../depends/nxtools \

include ../makefile.inc